import React, { useState, useEffect } from "react";
import { View, Text, ScrollView, RefreshControl, ActivityIndicator } from "react-native";
import { apiService } from "../../services/api";
import { Card } from "../../components/Card";
import { AIInsight } from "../../types";

export const LiteracyScreen = () => {
  const [insights, setInsights] = useState<AIInsight[]>([]);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);

  const loadInsights = async () => {
    try {
      setLoading(true);
      const res = await apiService.getEducatorAnalytics();
      setInsights(res.recent_insights || []);
    } catch (e: any) {
      console.warn("Failed to load insights for auditor:", e.message);
    } finally {
      setLoading(false);
    }
  };

  const handleRefresh = async () => {
    setRefreshing(true);
    await loadInsights();
    setRefreshing(false);
  };

  useEffect(() => {
    loadInsights();
  }, []);

  return (
    <ScrollView
      className="flex-1 bg-slate-900"
      contentContainerStyle={{ paddingHorizontal: 16, paddingTop: 16 }}
      refreshControl={
        <RefreshControl refreshing={refreshing} onRefresh={handleRefresh} tintColor="#4F46E5" />
      }
    >
      <View className="mb-6">
        <Text className="text-slate-400 text-xs font-semibold uppercase tracking-wider">AI Quality Auditing</Text>
        <Text className="text-slate-100 text-2xl font-black">Financial Literacy Monitor</Text>
      </View>

      <Card className="mb-6 bg-indigo-900/10 border border-indigo-500/20">
        <Text className="text-indigo-400 text-sm font-bold mb-1.5">Advisor Oversight Panel</Text>
        <Text className="text-slate-300 text-xs leading-relaxed">
          Monitor recent plain-language explanations generated by the local `Llama3` AI module. 
          Use this audit log to ensure the guidance provided by the virtual coach matches institution policies.
        </Text>
      </Card>

      <View className="mb-10">
        <Text className="text-slate-200 text-base font-bold mb-4">Recent Student Advisor Logs</Text>

        {loading && insights.length === 0 ? (
          <ActivityIndicator color="#4F46E5" size="small" />
        ) : insights.length === 0 ? (
          <Card className="items-center py-6">
            <Text className="text-slate-400 text-xs italic text-center">
              No AI queries generated by students yet.
            </Text>
          </Card>
        ) : (
          insights.map((ins) => {
            const date = new Date(ins.created_at).toLocaleDateString(undefined, {
              month: "short",
              day: "numeric",
              hour: "2-digit",
              minute: "2-digit"
            });
            return (
              <Card key={ins.chat_id} className="mb-4">
                <View className="mb-2">
                  <Text className="text-indigo-400 text-xs font-semibold">
                    Q: {ins.question}
                  </Text>
                  <Text className="text-slate-500 text-[10px] mt-1">{date}</Text>
                </View>

                <Text className="text-slate-100 text-sm italic leading-relaxed">
                  "A: {ins.response}"
                </Text>
              </Card>
            );
          })
        )}
      </View>
    </ScrollView>
  );
};

export default LiteracyScreen;
