"""
Dream Engine Router — GET /goal/{goal_id}/forecast

Returns a rule-engine-computed savings forecast for a specific goal, narrated
by the LLM in plain, encouraging language with one concrete lever to speed up
progress.

Architecture contract
---------------------
- Rule Engine FIRST: savings_velocity() and goal_forecast() are called before
  any LLM call. The AI only narrates numbers it receives — it never computes them.
- Goal ownership is verified before any data is returned (404 on miss or mismatch
  — never leaks whether another user's goal exists).
- READ-ONLY: no writes to Goal, Savings, or any other table in this router.
- On AIEngineError the endpoint raises HTTP 503. No mocked/fallback explanation.

Placement rationale
-------------------
New file `dream.py` following the project convention of one router file per
AI feature (mirrors coach.py, negotiator.py). The existing forecast.py is a
legacy stub that uses the old ai_service.call_ai pattern and is superseded by
this implementation.
"""

from __future__ import annotations

import datetime
import logging
from decimal import Decimal
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.database import get_db
from app.middleware.auth_middleware import get_current_user
from app.models.models import Goal, Savings, User
from app.services.ai_engine import AIEngineError, call_llama
from app.services.rule_engine import goal_forecast, savings_velocity
from app.utils.prompts import dream_engine_prompt

logger = logging.getLogger("sparechange_ai.dream")

router = APIRouter(prefix="/goal", tags=["Dream Engine"])

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
_VELOCITY_LOOKBACK_SAVINGS = 60  # max recent Savings rows to read for velocity

# ---------------------------------------------------------------------------
# Pydantic response model
# ---------------------------------------------------------------------------

class ForecastResponse(BaseModel):
    """Response for GET /goal/{goal_id}/forecast."""

    goal_id:        int
    goal_name:      str
    target_amount:  Decimal
    current_amount: Decimal
    forecast_date:  Optional[datetime.date] = Field(
        None,
        description="Projected completion date, or null if velocity is zero.",
    )
    velocity:       Decimal = Field(
        ...,
        description="Current monthly savings rate in INR (last 30 days).",
    )
    explanation:    str = Field(
        ...,
        description="LLM-generated encouraging forecast explanation.",
    )


# Resolve forward references for Pydantic v2
ForecastResponse.model_rebuild()


# ---------------------------------------------------------------------------
# GET /api/goal/{goal_id}/forecast
# ---------------------------------------------------------------------------

@router.get(
    "/{goal_id}/forecast",
    response_model=ForecastResponse,
    status_code=status.HTTP_200_OK,
    summary="Dream Engine — AI goal forecast",
    description=(
        "Returns the projected completion date for a savings goal and a "
        "personalised, encouraging explanation generated by the AI. "
        "Also suggests one concrete action to reach the goal sooner."
    ),
)
async def get_goal_forecast(
    goal_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
) -> ForecastResponse:
    """
    Flow
    ----
    1. Fetch goal — 404 if not found OR not owned by current user.
    2. Rule Engine: savings_velocity() from last-30-days Savings rows.
    3. Rule Engine: goal_forecast() → projected completion date.
    4. Prompt builder: dream_engine_prompt() with all computed values.
    5. AI Engine: call_llama() → encouraging plain-language explanation.
    6. Return { goal_id, goal_name, target_amount, current_amount,
                forecast_date, velocity, explanation }.
    """
    uid = current_user.user_id

    # ── 1. Fetch goal (ownership check) ──────────────────────────────────
    goal: Optional[Goal] = (
        db.query(Goal)
        .filter(
            Goal.goal_id == goal_id,
            Goal.user_id == uid,      # enforces ownership — 404 on mismatch
        )
        .first()
    )
    if goal is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Goal not found.",   # intentionally generic — no existence leak
        )

    target  = Decimal(str(goal.target))
    current = Decimal(str(goal.saved))

    logger.info(
        "dream.forecast | user_id=%d goal_id=%d target=₹%s saved=₹%s",
        uid, goal_id, target, current,
    )

    # ── 2. Rule Engine — savings velocity ────────────────────────────────
    recent_savings = (
        db.query(Savings)
        .filter(Savings.user_id == uid)
        .order_by(Savings.date.desc())          # type: ignore[attr-defined]
        .limit(_VELOCITY_LOOKBACK_SAVINGS)
        .all()
    )
    amounts = [Decimal(str(s.amount)) for s in recent_savings]
    velocity = savings_velocity(amounts, period_days=30)

    # ── 3. Rule Engine — projected date ──────────────────────────────────
    raw_forecast = goal_forecast(target, current, velocity)

    # Convert sentinel (9999-12-31) to None for the response
    if raw_forecast >= datetime.date(9999, 1, 1):
        forecast_date: Optional[datetime.date] = None
    else:
        forecast_date = raw_forecast

    logger.info(
        "dream.forecast | user_id=%d goal_id=%d velocity=₹%s/month forecast=%s",
        uid, goal_id, velocity, forecast_date,
    )

    # ── 4. Build prompt ──────────────────────────────────────────────────
    prompt = dream_engine_prompt(
        goal_name=goal.goal_name,
        target_amount=target,
        current_amount=current,
        forecast_date=raw_forecast,   # pass raw sentinel — prompts.py handles it
        velocity=velocity,
    )

    # ── 5. LLM call ──────────────────────────────────────────────────────
    try:
        explanation = await call_llama(
            system_prompt=(
                "You are SpareChange AI. You motivate college students about "
                "their savings goals in plain, upbeat language. Be specific — "
                "use the numbers provided. Suggest exactly one concrete action "
                "to reach the goal sooner (e.g. saving an extra ₹X/month). "
                "Keep your reply to 3 sentences or fewer."
            ),
            user_prompt=prompt,
        )
    except AIEngineError as exc:
        logger.error(
            "dream.forecast | user_id=%d goal_id=%d | AIEngineError: %s",
            uid, goal_id, exc.message,
        )
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=(
                "The Dream Engine is temporarily unavailable. "
                "Your forecast data is shown below — the AI explanation "
                "will be back shortly."
            ),
        ) from exc

    # ── 6. Return ─────────────────────────────────────────────────────────
    return ForecastResponse(
        goal_id=goal.goal_id,
        goal_name=goal.goal_name,
        target_amount=target,
        current_amount=current,
        forecast_date=forecast_date,
        velocity=velocity,
        explanation=explanation,
    )
